// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hashing-service.proto

// The name that will be used inside the code to call the service and messages

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HashingEncodeRequest struct {
	PlainText            string   `protobuf:"bytes,1,opt,name=plainText,proto3" json:"plainText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashingEncodeRequest) Reset()         { *m = HashingEncodeRequest{} }
func (m *HashingEncodeRequest) String() string { return proto.CompactTextString(m) }
func (*HashingEncodeRequest) ProtoMessage()    {}
func (*HashingEncodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4e738be27ad62b1, []int{0}
}

func (m *HashingEncodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashingEncodeRequest.Unmarshal(m, b)
}
func (m *HashingEncodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashingEncodeRequest.Marshal(b, m, deterministic)
}
func (m *HashingEncodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashingEncodeRequest.Merge(m, src)
}
func (m *HashingEncodeRequest) XXX_Size() int {
	return xxx_messageInfo_HashingEncodeRequest.Size(m)
}
func (m *HashingEncodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashingEncodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashingEncodeRequest proto.InternalMessageInfo

func (m *HashingEncodeRequest) GetPlainText() string {
	if m != nil {
		return m.PlainText
	}
	return ""
}

type HashingEncodeResponse struct {
	HashedText           string   `protobuf:"bytes,1,opt,name=hashedText,proto3" json:"hashedText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashingEncodeResponse) Reset()         { *m = HashingEncodeResponse{} }
func (m *HashingEncodeResponse) String() string { return proto.CompactTextString(m) }
func (*HashingEncodeResponse) ProtoMessage()    {}
func (*HashingEncodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4e738be27ad62b1, []int{1}
}

func (m *HashingEncodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashingEncodeResponse.Unmarshal(m, b)
}
func (m *HashingEncodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashingEncodeResponse.Marshal(b, m, deterministic)
}
func (m *HashingEncodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashingEncodeResponse.Merge(m, src)
}
func (m *HashingEncodeResponse) XXX_Size() int {
	return xxx_messageInfo_HashingEncodeResponse.Size(m)
}
func (m *HashingEncodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashingEncodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashingEncodeResponse proto.InternalMessageInfo

func (m *HashingEncodeResponse) GetHashedText() string {
	if m != nil {
		return m.HashedText
	}
	return ""
}

type HashingDecodeRequest struct {
	HashedText           string   `protobuf:"bytes,1,opt,name=hashedText,proto3" json:"hashedText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashingDecodeRequest) Reset()         { *m = HashingDecodeRequest{} }
func (m *HashingDecodeRequest) String() string { return proto.CompactTextString(m) }
func (*HashingDecodeRequest) ProtoMessage()    {}
func (*HashingDecodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4e738be27ad62b1, []int{2}
}

func (m *HashingDecodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashingDecodeRequest.Unmarshal(m, b)
}
func (m *HashingDecodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashingDecodeRequest.Marshal(b, m, deterministic)
}
func (m *HashingDecodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashingDecodeRequest.Merge(m, src)
}
func (m *HashingDecodeRequest) XXX_Size() int {
	return xxx_messageInfo_HashingDecodeRequest.Size(m)
}
func (m *HashingDecodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashingDecodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashingDecodeRequest proto.InternalMessageInfo

func (m *HashingDecodeRequest) GetHashedText() string {
	if m != nil {
		return m.HashedText
	}
	return ""
}

type HashingDecodeResponse struct {
	PlainText            string   `protobuf:"bytes,1,opt,name=plainText,proto3" json:"plainText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashingDecodeResponse) Reset()         { *m = HashingDecodeResponse{} }
func (m *HashingDecodeResponse) String() string { return proto.CompactTextString(m) }
func (*HashingDecodeResponse) ProtoMessage()    {}
func (*HashingDecodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4e738be27ad62b1, []int{3}
}

func (m *HashingDecodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashingDecodeResponse.Unmarshal(m, b)
}
func (m *HashingDecodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashingDecodeResponse.Marshal(b, m, deterministic)
}
func (m *HashingDecodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashingDecodeResponse.Merge(m, src)
}
func (m *HashingDecodeResponse) XXX_Size() int {
	return xxx_messageInfo_HashingDecodeResponse.Size(m)
}
func (m *HashingDecodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashingDecodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashingDecodeResponse proto.InternalMessageInfo

func (m *HashingDecodeResponse) GetPlainText() string {
	if m != nil {
		return m.PlainText
	}
	return ""
}

func init() {
	proto.RegisterType((*HashingEncodeRequest)(nil), "proto.HashingEncodeRequest")
	proto.RegisterType((*HashingEncodeResponse)(nil), "proto.HashingEncodeResponse")
	proto.RegisterType((*HashingDecodeRequest)(nil), "proto.HashingDecodeRequest")
	proto.RegisterType((*HashingDecodeResponse)(nil), "proto.HashingDecodeResponse")
}

func init() { proto.RegisterFile("hashing-service.proto", fileDescriptor_a4e738be27ad62b1) }

var fileDescriptor_a4e738be27ad62b1 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x48, 0x2c, 0xce,
	0xc8, 0xcc, 0x4b, 0xd7, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x26, 0x5c, 0x22, 0x1e, 0x10, 0x79, 0xd7, 0xbc, 0xe4, 0xfc,
	0x94, 0xd4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x19, 0x2e, 0xce, 0x82, 0x9c, 0xc4,
	0xcc, 0xbc, 0x90, 0xd4, 0x8a, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84, 0x80, 0x92,
	0x39, 0x97, 0x28, 0x9a, 0xae, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x39, 0x2e, 0x2e, 0x90,
	0x75, 0xa9, 0x29, 0x48, 0xfa, 0x90, 0x44, 0x94, 0xcc, 0xe0, 0xd6, 0xb9, 0xa4, 0x22, 0x5b, 0x47,
	0x48, 0x9f, 0x29, 0xdc, 0x42, 0x98, 0x3e, 0xa8, 0x85, 0x78, 0xdd, 0x69, 0x34, 0x8b, 0x91, 0x8b,
	0x0f, 0xaa, 0x2f, 0x18, 0xe2, 0x7b, 0x21, 0x67, 0x2e, 0x36, 0x88, 0x9b, 0x85, 0xa4, 0x21, 0x21,
	0xa1, 0x87, 0xcd, 0xff, 0x52, 0x32, 0xd8, 0x25, 0xa1, 0xb6, 0x3a, 0x73, 0xb1, 0x41, 0xdc, 0x81,
	0x6e, 0x08, 0x8a, 0xaf, 0xd0, 0x0d, 0x41, 0x75, 0x7a, 0x12, 0x1b, 0x58, 0xd2, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xb2, 0xc9, 0x29, 0x56, 0xa1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HashingServiceClient is the client API for HashingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HashingServiceClient interface {
	Encode(ctx context.Context, in *HashingEncodeRequest, opts ...grpc.CallOption) (*HashingEncodeResponse, error)
	Decode(ctx context.Context, in *HashingDecodeRequest, opts ...grpc.CallOption) (*HashingDecodeResponse, error)
}

type hashingServiceClient struct {
	cc *grpc.ClientConn
}

func NewHashingServiceClient(cc *grpc.ClientConn) HashingServiceClient {
	return &hashingServiceClient{cc}
}

func (c *hashingServiceClient) Encode(ctx context.Context, in *HashingEncodeRequest, opts ...grpc.CallOption) (*HashingEncodeResponse, error) {
	out := new(HashingEncodeResponse)
	err := c.cc.Invoke(ctx, "/proto.HashingService/Encode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashingServiceClient) Decode(ctx context.Context, in *HashingDecodeRequest, opts ...grpc.CallOption) (*HashingDecodeResponse, error) {
	out := new(HashingDecodeResponse)
	err := c.cc.Invoke(ctx, "/proto.HashingService/Decode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashingServiceServer is the server API for HashingService service.
type HashingServiceServer interface {
	Encode(context.Context, *HashingEncodeRequest) (*HashingEncodeResponse, error)
	Decode(context.Context, *HashingDecodeRequest) (*HashingDecodeResponse, error)
}

// UnimplementedHashingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHashingServiceServer struct {
}

func (*UnimplementedHashingServiceServer) Encode(ctx context.Context, req *HashingEncodeRequest) (*HashingEncodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encode not implemented")
}
func (*UnimplementedHashingServiceServer) Decode(ctx context.Context, req *HashingDecodeRequest) (*HashingDecodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decode not implemented")
}

func RegisterHashingServiceServer(s *grpc.Server, srv HashingServiceServer) {
	s.RegisterService(&_HashingService_serviceDesc, srv)
}

func _HashingService_Encode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashingEncodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashingServiceServer).Encode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HashingService/Encode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashingServiceServer).Encode(ctx, req.(*HashingEncodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashingService_Decode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashingDecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashingServiceServer).Decode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HashingService/Decode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashingServiceServer).Decode(ctx, req.(*HashingDecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HashingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HashingService",
	HandlerType: (*HashingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encode",
			Handler:    _HashingService_Encode_Handler,
		},
		{
			MethodName: "Decode",
			Handler:    _HashingService_Decode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashing-service.proto",
}
